name: S3 Deployment
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.4.0]
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
    - name: Checkout
      uses: actions/checkout@v2
      with:
          ref: ${{ github.ref }}
    - name: Create .env
      run: |
        echo "USER_POOL_ID=${{ secrets.USER_POOL_ID }}\n" > "./.env"
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}\n" >> "./.env"
        echo "API_KEY=${{ secrets.API_KEY }}" >> "./.env"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: Build
      run: npm run build --if-present
    - name: Deploy to S3
      run: |
          aws s3 cp "./.env" "s3://admin.sakaba.link/.env"
          aws s3 cp "dist/bundle.js" "s3://admin.sakaba.link/dist/bundle.js"
          aws s3 cp "index.html" "s3://admin.sakaba.link/index.html"
          aws s3 cp "index.min.css" "s3://admin.sakaba.link/index.min.css"
          aws s3 cp "favicon.ico" "s3://admin.sakaba.link/favicon.ico"
    - name: CloudFront Invalidation
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths "/*"
